---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krr-mcp
  namespace: krr-mcp
  labels:
    app: krr-mcp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krr-mcp-reader
  labels:
    app: krr-mcp
rules:
  # KRR needs to read pod metrics and resource information
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
      - persistentvolumeclaims
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  # Metrics API access
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs: ["get", "list"]

  # HPA access (for checking autoscaling configs)
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krr-mcp-reader
  labels:
    app: krr-mcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krr-mcp-reader
subjects:
  - kind: ServiceAccount
    name: krr-mcp
    namespace: krr-mcp
