apiVersion: v1
kind: Service
metadata:
  name: krr-mcp
  namespace: krr-mcp
  labels:
    app: krr-mcp
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: krr-mcp
